In [107]:
#grouplens

import pandas as pd
import numpy as np

def pearson(x, y): #ピアソンの相関係数(重み)
    w_1, w_2 = [], []
    tmp = x * y
    for i in range(len(tmp)):
        if tmp[i] > 0 and tmp[i] <= 25 :
            w_1.append(x[i])
            w_2.append(y[i])
    
    return np.corrcoef(w_1, w_2)[0,1]

def average(bar):
    total,fig = 0, 0
    for i in bar:
        if i!=-9999:
            total+=i
            fig+=1
    return total/fig

def evaluate(a,i,trainig,weighit):
    w, tmp =0, 0
    for u in range(training.shape[0]):
        if a!=u and training[u,i]!=-9999 :
            w+=abs(weight[a][u])
            tmp+= (training[u,i]-average(training[u]))*weight[a][u]
    
    return average(training[a])+tmp/w


training_df = pd.read_csv("kinki_training.csv",  encoding="shift-jis", header=None, index_col=0)
test_df = pd.read_csv("kinki_test.csv",  encoding="shift-jis", header=None,index_col=0)
training_df = training_df.drop(index=["回答者番号"])
test_df = test_df.drop(index=["回答者番号"])
training = training_df.to_numpy()

#重み
weight = [[0 for i in range(training.shape[0])]for j in range(training.shape[0])]
#予測値
predict= [[0 for i in range(training.shape[1])]for j in range(training.shape[0])]

#training.shape(70, 21) ユーザ数×アイテム数
training = training.astype('int16')

for a in range(training.shape[0]):
    for u in range(training.shape[0]):
        if a==u:
            continue    
        weight[a][u] = pearson(training[a], training[u])
     
for a in range(training.shape[0]):
    for i in range(training.shape[1]):
        predict[a][i] = evaluate(a,i,training,weight)
    
predict_df = pd.DataFrame(predict)
predict_df
weight_df = pd.DataFrame(weight)
#weight_df

C:\Users\yuta8\anaconda3\Lib\site-packages\numpy\lib\function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Users\yuta8\anaconda3\Lib\site-packages\numpy\lib\function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.888168,1.112024,1.011861,0.967594,1.155044,1.571850,1.008309,1.575344,1.697180,0.992822,...,1.163001,0.791172,1.134098,1.786789,1.554183,1.866224,1.975603,1.532549,1.796870,1.175291
1,3.254944,3.123168,3.221518,3.395590,3.162214,2.150490,3.275427,2.400781,3.024907,3.637236,...,3.594429,3.386936,3.133891,2.793625,2.283741,2.332186,2.298660,2.165027,3.002311,2.798786
2,4.241149,4.019038,3.908464,4.360358,4.258710,5.170314,4.169408,4.877187,4.400170,3.593306,...,3.658488,3.840587,4.083733,4.362252,5.023070,4.738118,4.851322,4.823261,3.666250,4.513502
3,3.779802,3.401819,3.557602,3.569017,3.562832,4.206345,3.443583,3.840417,3.978095,2.784832,...,2.893736,3.243082,3.664647,4.163533,3.937940,3.660368,3.820505,3.952048,3.398942,3.714191
4,3.001184,2.890007,2.626110,2.700648,2.884284,3.284602,2.973593,4.158462,3.281233,3.029268,...,2.733109,2.546250,3.083081,3.802124,3.328829,3.485438,3.666267,3.503294,2.845567,3.187871
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,NaN,NaN,NaN,NaN,2.732973,3.056051,2.832509,NaN,2.134886,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.472809,NaN
66,3.377682,3.744480,3.368896,4.091177,3.796336,3.289122,4.414764,3.678099,3.923310,4.795564,...,4.311722,3.996077,3.650722,3.788328,3.607976,3.779223,3.857443,3.382901,4.085490,3.655442
67,NaN,NaN,NaN,NaN,3.354515,2.764250,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4.175054,NaN,NaN,NaN,NaN,NaN,NaN
68,2.840437,3.019411,3.114692,2.841873,2.944074,3.884373,2.961673,3.941701,3.114495,2.925194,...,2.517612,2.432483,3.054758,3.359025,3.795249,3.700410,3.766809,3.768838,3.101380,3.583073
69,3.929994,3.850245,3.824903,3.867988,3.788350,4.526771,3.831288,4.791255,3.932033,3.263567,...,3.271251,3.606621,3.921055,4.269222,4.550410,4.436882,4.579707,4.589938,3.780365,4.174098

In [182]:
#パーソナライズされていない手法

def evaluate_noper_onlyave(a,i,training):
    tmp, n = 0, 0
    for u in range(training.shape[0]):
        if training[u,i]!=-9999 :
            tmp+=training[u,i]
            n+=1
    return tmp/n

def evaluate_noper_ave(a,i,training):
    tmp, n = 0, 0
    for u in range(training.shape[0]):
        if training[u,i]!=-9999 :
            tmp+=training[u,i]-average(training[u])
            n+=1

    return average(training[a])+tmp/n


predict_noper_onave = [[0 for i in range(training.shape[1])]for j in range(training.shape[0])]
predict_noper_ave = [[0 for i in range(training.shape[1])]for j in range(training.shape[0])]

for a in range(training.shape[0]):
    for i in range(training.shape[1]):
        predict_noper_onave[a][i] =  evaluate_noper_onlyave(a,i,training)
        predict_noper_ave[a][i] = evaluate_noper_ave(a,i,training)
        
predict_noper_onave_df = pd.DataFrame(predict_noper_onave)
predict_noper_ave_df = pd.DataFrame(predict_noper_ave)
predict_noper_onave_df

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,3.414634,3.038462,3.304348,3.24,3.1,2.789474,3.323529,4.104167,2.933333,3.393443,...,3.206897,2.708333,3.771429,3.837209,2.857143,3.217391,3.421875,3.185185,3.0625,4.040816
1,3.414634,3.038462,3.304348,3.24,3.1,2.789474,3.323529,4.104167,2.933333,3.393443,...,3.206897,2.708333,3.771429,3.837209,2.857143,3.217391,3.421875,3.185185,3.0625,4.040816
2,3.414634,3.038462,3.304348,3.24,3.1,2.789474,3.323529,4.104167,2.933333,3.393443,...,3.206897,2.708333,3.771429,3.837209,2.857143,3.217391,3.421875,3.185185,3.0625,4.040816
3,3.414634,3.038462,3.304348,3.24,3.1,2.789474,3.323529,4.104167,2.933333,3.393443,...,3.206897,2.708333,3.771429,3.837209,2.857143,3.217391,3.421875,3.185185,3.0625,4.040816
4,3.414634,3.038462,3.304348,3.24,3.1,2.789474,3.323529,4.104167,2.933333,3.393443,...,3.206897,2.708333,3.771429,3.837209,2.857143,3.217391,3.421875,3.185185,3.0625,4.040816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,3.414634,3.038462,3.304348,3.24,3.1,2.789474,3.323529,4.104167,2.933333,3.393443,...,3.206897,2.708333,3.771429,3.837209,2.857143,3.217391,3.421875,3.185185,3.0625,4.040816
66,3.414634,3.038462,3.304348,3.24,3.1,2.789474,3.323529,4.104167,2.933333,3.393443,...,3.206897,2.708333,3.771429,3.837209,2.857143,3.217391,3.421875,3.185185,3.0625,4.040816
67,3.414634,3.038462,3.304348,3.24,3.1,2.789474,3.323529,4.104167,2.933333,3.393443,...,3.206897,2.708333,3.771429,3.837209,2.857143,3.217391,3.421875,3.185185,3.0625,4.040816
68,3.414634,3.038462,3.304348,3.24,3.1,2.789474,3.323529,4.104167,2.933333,3.393443,...,3.206897,2.708333,3.771429,3.837209,2.857143,3.217391,3.421875,3.185185,3.0625,4.040816
69,3.414634,3.038462,3.304348,3.24,3.1,2.789474,3.323529,4.104167,2.933333,3.393443,...,3.206897,2.708333,3.771429,3.837209,2.857143,3.217391,3.421875,3.185185,3.0625,4.040816

In [157]:
#平均絶対誤差(MAE)
import math

def MAE(test,predict):
    tmp,n=0,0
    for j in range(test.shape[0]):
        if not math.isnan(predict[j][test[j,0]-1]):
            tmp +=abs(predict[j][test[j,0]-1]-test[j,1])
            n+=1
    return tmp/n

test = test_df.to_numpy()
test = test.astype("int8")
mae_1=MAE(test,predict)#grouplens
mae_2=MAE(test,predict_noper_onave)#パーソナライズされていない手法（予測値として平均値）
mae_3=MAE(test,predict_noper_ave)#パーソナライズされていない手法（予測値としてユーザごとの平均からの偏差）

print("パーソナライズされた手法")
print("grouplensでの予測の平均絶対誤差：",mae_1)
print("\nパーソナライズされていない手法")
print("予測値としてすべてのユーザの評価値の平均値を用いたものの平均絶対誤差：",mae_2)
print("予測値としてユーザごとの平均値からの偏差を用いたものの平均絶対誤差：",mae_3)

パーソナライズされた手法
grouplensでの予測の平均絶対誤差： 0.6092222105358573

パーソナライズされていない手法
予測値としてすべてのユーザの評価値の平均値を用いたものの平均絶対誤差： 0.7917626697844835
予測値としてユーザごとの平均値からの偏差を用いたものの平均絶対誤差： 0.6452070201862261

In [174]:
#ROC-4

N=np.count_nonzero(test[:,1]>=4)
M=np.array(predict)
M=np.count_nonzero(M>=4)
print(M/N)

8.375